import Head from "next/head";
import { useState, useEffect } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
// import { Auth } from "../hooks/auth";

import Post from "../components/Post";
import PostForm from "../components/PostForm";
import Bio from "../components/Bio/Bio";

export default function Home({ posts: defaultPosts }) {
  //posts rename to default posts
  // const { user, logIn, logOut } = Auth();
  // console.log("user", user);

  const [posts, updatePosts] = useState(defaultPosts);

  async function handleOnSubmit(data, e) {
    e.preventDefault();
    console.log("data", data);
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/posts`,
      {
        method: "POST",
        body: JSON.stringify(data),
      }
    );
    const responseGet = await fetch(
      `${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/posts`
    );
    const { posts } = await responseGet.json();
    updatePosts(posts);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Daimer's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {!user && (
        <>
          <p>
            <button onClick={logIn}>Log In</button>
          </p>
        </>
      )}
      {user && (
        <>
          <p>
            <button onClick={logOut}>Log Out</button>
          </p>
        </>
      )} */}
      <main className={styles.main}>
        <div className={styles.bio}>
          <Bio
            img="https://images.pexels.com/photos/9938444/pexels-photo-9938444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
            name="Daimer Haily"
            tagline="How you doing?"
            role="Developer Advocate @ Uttam"
          />
        </div>
        <h1 className={styles.title}>Daimer's Posts</h1>
        <ul className={styles.posts}>
          {posts.map((post) => (
            <li key={post.id}>
              <Post
                content={post.content}
                date={new Intl.DateTimeFormat("en-US", {
                  dateStyle: "short",
                  timeStyle: "short",
                }).format(new Date(post.date))}
              />
            </li>
          ))}
        </ul>
        <PostForm onSubmit={handleOnSubmit} />
        {/* {user && <></>} */}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/posts`
  );
  const { posts } = await response.json();
  return {
    props: {
      posts: posts,
    },
  };
}

//Bugs
//1
//process.env not workings. cannot able to access .env.local file. value undefined. response undefined
//solution: everything was good , hust needed to restart the server
